{% set version = "2021.09.08" %}

package:
  name: pangeo-notebook
  version: {{ version }}

build:
  number: 1
  noarch: generic

requirements:
  run:
    - pangeo-dask =2021.08.21
    - dask-labextension =5.1.0
    - ipywidgets =7.6.4
    - jupyter-server-proxy =3.1.0
    - jupyterhub-singleuser =1.4.2
    - jupyterlab =3.1.10
    - nbgitpuller =1.0.2
    - rise
    - ipytree

test:
  commands:
    - jupyter -h

about:
  home: http://pangeo.io
  license: MIT
  license_file: LICENSE
  summary: "pangeo notebook dependencies"

extra:
  recipe-maintainers:
    - scottyhq 
    - jhamman
    - TomAugspurger
