{% set version = "0.0.2" %}

package:
  name: pangeo-notebook
  version: {{ version }}

build:
  number: 2
  noarch: generic

requirements:
  run:
    - pangeo-dask =0.0.2
    - dask-gateway =0.6*
    - dask-labextension =1.1*
    - jupyter-server-proxy =1.2*
    - jupyterhub =1.1*
    - jupyterlab =1.2*
    - nbgitpuller =0.8*

test:
  commands:
    - jupyter -h

about:
  home: http://pangeo.io
  license: MIT
  license_file: LICENSE
  summary: "pangeo notebook dependencies"

extra:
  recipe-maintainers:
    - scottyhq 
    - jhamman
