{% set version = "2023.09.18" %}

package:
  name: pangeo-notebook
  version: {{ version }}

build:
  number: 0
  noarch: generic

requirements:
  run:
    - pangeo-dask =2023.09.17
    - dask-labextension =7.0.0
    - ipywidgets =8.1.1
    - jupyter-server-proxy =4.0.0
    - jupyterhub-singleuser =4.0.2
    - jupyterlab =4.0.6
    - nbgitpuller =1.2.0

test:
  commands:
    - jupyter -h

about:
  home: http://pangeo.io
  license: MIT
  license_file: LICENSE
  summary: "pangeo notebook dependencies"

extra:
  recipe-maintainers:
    - yuvipanda
    - scottyhq 
    - jhamman
    - TomAugspurger
