{% set version = "2023.07.10" %}

package:
  name: pangeo-notebook
  version: {{ version }}

build:
  number: 0
  noarch: generic

requirements:
  run:
    - pangeo-dask =2023.07.10
    - dask-labextension =6.1.0
    - ipywidgets =8.0.7
    - jupyter-server-proxy =4.0.0
    - jupyterhub-singleuser =4.0.1
    - jupyterlab <4
    - nbgitpuller =1.1.1

test:
  commands:
    - jupyter -h

about:
  home: http://pangeo.io
  license: MIT
  license_file: LICENSE
  summary: "pangeo notebook dependencies"

extra:
  recipe-maintainers:
    - yuvipanda
    - scottyhq 
    - jhamman
    - TomAugspurger
