{% set version = "2023.03.28" %}

package:
  name: pangeo-notebook
  version: {{ version }}

build:
  number: 0
  noarch: generic

requirements:
  run:
    - pangeo-dask =2023.03.11
    - dask-labextension =6.1.0
    - ipywidgets =8.0.5
    - jupyter-server-proxy =3.2.2
    - jupyterhub-singleuser =3.1.1
    - jupyterlab =3.6.2
    - nbgitpuller =1.1.1

test:
  commands:
    - jupyter -h

about:
  home: http://pangeo.io
  license: MIT
  license_file: LICENSE
  summary: "pangeo notebook dependencies"

extra:
  recipe-maintainers:
    - yuvipanda
    - scottyhq 
    - jhamman
    - TomAugspurger
