{% set version = "2024.04.16" %}

package:
  name: pangeo-notebook
  version: {{ version }}

build:
  number: 0
  noarch: generic

requirements:
  run:
    - pangeo-dask =2024.04.05
    - dask-labextension =7.0.0
    - ipywidgets =8.1.2
    - jupyter-server-proxy =4.1.2
    - jupyterhub-singleuser =4.1.5
    - jupyterlab =4.1.6
    - nbgitpuller =1.2.1

test:
  commands:
    - jupyter -h

about:
  home: http://pangeo.io
  license: MIT
  license_file: LICENSE
  summary: "pangeo notebook dependencies"

extra:
  recipe-maintainers:
    - yuvipanda
    - scottyhq 
    - jhamman
    - TomAugspurger
