{% set version = "2024.09.01" %}

package:
  name: pangeo-notebook
  version: {{ version }}

build:
  number: 0
  noarch: generic

requirements:
  run:
    - pangeo-dask =2024.8.31
    - dask-labextension =7.0.0
    - ipywidgets =8.1.5
    - jupyter-server-proxy =4.4.0
    - jupyterhub-singleuser =5.1.0
    - jupyterlab =4.2.5
    - nbgitpuller =1.2.1

test:
  commands:
    - jupyter -h

about:
  home: http://pangeo.io
  license: MIT
  license_file: LICENSE
  summary: "pangeo notebook dependencies"

extra:
  recipe-maintainers:
    - yuvipanda
    - scottyhq 
    - jhamman
    - TomAugspurger
